[theme]
primaryColor = "#E31E32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false